variables:
  PROJECT: 'Xenirio.Component.Gutenberg'
  
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe'
  MSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'

stages:
  - build
  - test
  - pack
  - deploy

build_job:
  stage: build
  tags:
    - 'gutenberg'
    - 'nuget'
    - 'powershell'
  #only:
  #  - tags
  script:
    - '"%NUGET_PATH%" restore %PROJECT%\packages.config -PackagesDirectory ..\packages'
    - '"%MSBUILD_PATH%" %PROJECT%\%PROJECT%.csproj /p:Configuration=Release'
  artifacts:
    expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
    paths: #artifacts paths will leave files inside that describe below as 'artifacts' and will not remove when starting of next stage
      - '%PROJECT%/bin/'

test_job:
  stage: test
  tags:
    - 'gutenberg'
    - 'nuget'
    - 'powershell'
  #only:
  #  - tags
  script:
    - '"%NUGET_PATH%" restore %PROJECT%.Test\packages.config -PackagesDirectory ..\packages'
    - '"%MSBUILD_PATH%" %PROJECT%.Test\%PROJECT%.Test.csproj /p:Configuration=Release'
    - '"%MSTEST_PATH%" %PROJECT%.Test\bin\Release\%PROJECT%.Test.dll'
  artifacts:
    expire_in: 1 week
    paths:
      - '%PROJECT%/bin/'
      - 'TestResults/'
  dependencies:
    - build_job

pack_job:
  stage: pack
  tags:
    - 'gutenberg'
    - 'nuget'
    - 'powershell'
  only:
    - tags
  script:
    - '"%NUGET_PATH%" pack .\%PROJECT%\%PROJECT%.nuspec'
  artifacts:
    expire_in: 1 week
    paths:
      - '*.nupkg'
  
  dependencies:
    - test_job

deploy_job:
  stage: deploy
  tags:
    - 'gutenberg'
    - 'nuget'
    - 'powershell'
  only:
    - tags
  script:
    - '"%NUGET_PATH%" push %PROJECT%.%CI_COMMIT_TAG%.nupkg %DEPLOY_KEY% -source %DEPLOY_AT%'
  dependencies:
    - pack_job