variables:
  PROJECT: 'Xenirio.Component.Gutenberg'
  TEST_AT: 'Xenirio.Component.Gutenberg.Test\bin\Release'
  DEPLOY_AT: 'https://handshakes-nuget.azurewebsites.net/nuget'
  DEPLOY_KEY: '9B0904D2-FD50-48CE-9891-7091E956B697'
  
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe'
  MSTEST_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'

stages:
  - build
  - test
  - pack
  - deploy

build_job:
  stage: build
  only:
    - tags
  script:
    - '"%NUGET_PATH%" restore' # restore Nuget dependencies
    - '"%MSBUILD_PATH%" %PROJECT%.sln /p:Configuration=Release' # build the project
  artifacts:
    expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
    paths: #artifacts paths will leave files inside that describe below as 'artifacts' and will not remove when starting of next stage
      - '%PROJECT%/bin/'
      - '%PROJECT%.Test/bin/'

test_job:
  stage: test
  only:
    - tags
  script:
    - '"%MSTEST_PATH%" %TEST_AT%\Xenirio.Component.Gutenberg.Test.dll' # running unit tests
  artifacts:
    expire_in: 1 week
    paths:
      - '%PROJECT%/bin/'
      - 'TestResults/'
  dependencies:
    - build_job

pack_job:
  stage: pack
  only:
    - tags
  script:
    - '"%NUGET_PATH%" pack .\%PROJECT%\%PROJECT%.nuspec'
  artifacts:
    expire_in: 1 week
    paths:
      - '*.nupkg'
  
  dependencies:
    - test_job

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - '"%NUGET_PATH%" push %PROJECT%.%CI_COMMIT_TAG%.nupkg %DEPLOY_KEY% -source %DEPLOY_AT%'
  dependencies:
    - pack_job